clusterGroup:
  name: prod
  namespaces:
    external-secrets:
    external-secrets-operator:
      operatorGroup: true
      targetNamespaces: []
    openshift-cnv:
      operatorGroup: true
      targetNamespaces:
        - openshift-cnv
    openshell-agents:
      operatorGroup: true
      targetNamespaces:
        - openshell-agents
    rhdh:
    rhdh-operator:
      operatorGroup: true
      targetNamespaces: []
    # ansible-automation-platform:
    #   operatorGroup: true
    #   targetNamespaces: []
    redhat-ods-operator:
      operatorGroup: true
      targetNamespaces: []
    vault:
  subscriptions:
    eso:
      name: openshift-external-secrets-operator
      namespace: external-secrets-operator
      channel: stable-v1
    openshift-virtualization:
      name: kubevirt-hyperconverged
      namespace: openshift-cnv
      channel: stable
    rhbk:
      name: rhbk-operator
      namespace: openshell-agents
      channel: stable-v26
    rhdh:
      name: rhdh
      namespace: rhdh-operator
      channel: fast
    # aap:
    #   name: ansible-automation-platform-operator
    #   namespace: ansible-automation-platform
    #   channel: stable-2.5
    openshift-ai:
      name: rhods-operator
      namespace: redhat-ods-operator
      channel: fast
  applications:
    openshift-external-secrets:
      name: openshift-external-secrets
      namespace: external-secrets
      chart: openshift-external-secrets
      chartVersion: 0.0.*
    vault:
      name: vault
      namespace: vault
      chart: hashicorp-vault
      chartVersion: 0.1.*
    openshift-cnv:
      name: openshift-cnv
      namespace: openshift-cnv
      path: charts/openshift-cnv
    openshell-keycloak:
      name: openshell-keycloak
      namespace: openshell-agents
      path: charts/openshell-keycloak
    pattern-secrets:
      name: pattern-secrets
      namespace: openshell-agents
      path: charts/pattern-secrets
    governance-policy:
      name: governance-policy
      namespace: openshell-agents
      path: charts/governance-policy
    governance-interceptor:
      name: governance-interceptor
      namespace: openshell-agents
      path: charts/governance-interceptor
    openshell-rhdh:
      name: openshell-rhdh
      namespace: rhdh
      path: charts/openshell-rhdh
    openshell-saw:
      name: openshell-saw
      namespace: openshell-agents
      path: charts/openshell-saw
      extraValueFiles:
        - /overrides/openshell-saw.yaml
