apiVersion: saw.redhat.com/v1alpha1
kind: Providers
metadata:
  name: default
  profile: data-science
spec:
  providers:
    - name: nvidia
      type: nvidia
      credentialRef: nvidia
    - name: brave
      type: brave
      credentialRef: brave
