apiVersion: saw.redhat.com/v1alpha1
kind: Sandboxes
metadata: {}
spec:
  sandboxes:
    - name: notebook
      type: openclaw
      enabled: true
      image: quay.io/rh-ai-quickstart/openclaw-openshell@sha256:a9113294df7bef4794b72c10415d9b883064d01ca044d6938269d601061b435f
      data:
        name: notebook-data
        mountPath: /sandbox/persist
        retainOnDelete: true
      providers:
        - nvidia
    - name: cuda-sandbox
      type: nemoclaw
      enabled: false
      agent: openclaw
      image: quay.io/rh-ai-quickstart/nemoclaw-sandbox:latest
      providers:
        - nvidia
    - name: toolbox
      type: generic
      enabled: false
      image: base
      providers:
        - nvidia
