{{- if .Values.route.gateway.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "openshell-k8s.fullname" . }}-gateway
  labels:
    {{- include "openshell-k8s.labels" . | nindent 4 }}
spec:
  to:
    kind: Service
    name: {{ include "openshell-k8s.fullname" . }}-gateway
    weight: 100
  port:
    targetPort: grpc
  tls:
    termination: passthrough
{{- end }}
