apiVersion: v1
kind: Service
metadata:
  name: {{ include "saw-codex-api.fullname" . }}
  labels:
    {{- include "saw-codex-api.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "saw-codex-api.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: http
      protocol: TCP
