source:
  git:
    uri: "https://github.com/NVIDIA/NemoClaw.git"
    ref: "15069f9262d52b74d8916b7a0d7969a9ae4d3ee1"

build:
  nodeImage: "node:22-trixie-slim"
  maxOpenshellVersion: "0.0.99"

output:
  imageStreamTag: "nemoclaw-cli:latest"
