source:
  git:
    uri: "https://github.com/NVIDIA/NemoClaw.git"
    ref: "588bb6db9b1132266840e4604fa16c2a4912cbfc"

build:
  nodeImage: "node:22-trixie-slim"
  maxOpenshellVersion: "0.0.99"

output:
  imageStreamTag: "nemoclaw-cli:latest"
