apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshell-keycloak.fullname" . }}
  labels:
    {{- include "openshell-keycloak.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "openshell-keycloak.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
