{{- if and .Values.enabled (eq (include "governance.engine" .) "interceptor") }}
apiVersion: v1
kind: Service
metadata:
  name: governance-interceptor
  labels:
    app.kubernetes.io/name: governance-interceptor
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: grpc
      port: {{ .Values.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    app.kubernetes.io/name: governance-interceptor
{{- end }}
