#!/usr/bin/env python3
"""Bundle shared domain contracts into Helm's required values.schema.json.

Helm/Argo must validate without a network schema fetch or a custom plugin.
Run with --check in CI; regenerate after changing files under schemas/.
"""

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def bundled_schema():
    schema = json.loads((ROOT / "schemas/saw-blueprint-values.schema.json").read_text())
    schema["$comment"] = "GENERATED by tools/saw/render_chart_schema.py; edit schemas/, not this file."
    return json.dumps(schema, indent=2) + "\n"


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    target = ROOT / "charts/saw-blueprint/values.schema.json"
    expected = bundled_schema()
    if args.check:
        if not target.exists() or target.read_text() != expected:
            parser.exit(1, "Helm schema is stale: run python3 tools/saw/render_chart_schema.py\n")
    else:
        target.write_text(expected)


if __name__ == "__main__":
    main()
