apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: inference
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: inference
    template:
      type: Opaque
      engineVersion: v2
      data:
        provider: {{ printf "{{ .provider }}" | quote }}
        model: {{ printf "{{ .model }}" | quote }}
        api_key: {{ printf "{{ .api_key }}" | quote }}
        url: {{ printf "{{ index . \"url\" | default \"\" }}" | quote }}
  dataFrom:
    - extract:
        key: {{ .Values.vaultPrefix }}/inference
