apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: nvidia
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: nvidia
    template:
      type: Opaque
      data:
        api_key: {{ printf "{{ .api_key }}" | quote }}
  data:
    - secretKey: api_key
      remoteRef:
        key: {{ .Values.vaultPrefix }}/nvidia
        property: api_key
