apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openshell-ssh-pubkey
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: openshell-ssh-pubkey
    template:
      type: Opaque
      data:
        ssh-publickey: {{ printf "{{ .public_key }}" | quote }}
  data:
    - secretKey: public_key
      remoteRef:
        key: {{ .Values.sshVaultPrefix | default .Values.vaultPrefix }}/ssh
        property: public_key
