apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: openshell-aap-ssh
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: openshell-aap-ssh
    template:
      type: Opaque
      data:
        key: {{ printf "{{ .private_key }}" | quote }}
        public_key: {{ printf "{{ .public_key }}" | quote }}
  data:
    - secretKey: private_key
      remoteRef:
        key: {{ .Values.vaultPrefix }}/ssh
        property: private_key
    - secretKey: public_key
      remoteRef:
        key: {{ .Values.vaultPrefix }}/ssh
        property: public_key
