apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vertex
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: vertex
    template:
      type: Opaque
      data:
        sa_json: {{ printf "{{ .sa_json }}" | quote }}
  data:
    - secretKey: sa_json
      remoteRef:
        key: {{ .Values.vaultPrefix }}/vertex
        property: sa_json
