{{- if has "web-search" (.Values.secrets | default list) }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: web-search
spec:
  refreshInterval: {{ .Values.refreshInterval }}
  secretStoreRef:
    name: {{ .Values.secretStoreRef.name }}
    kind: {{ .Values.secretStoreRef.kind }}
  target:
    name: web-search
  dataFrom:
    - extract:
        key: {{ .Values.vaultPrefix }}/web-search
{{- end }}
