#!/usr/bin/env python3
"""Build and sign the APF policy bundle from charts/governance-policy.

APF (Agent Policy Fabric) serves a signed bundle instead of the plain
governance-policy ConfigMaps. This script keeps governance-policy the single
source of truth: it translates policy.yaml and profiles/*.yaml into APF's
SandboxPolicy / Provider documents, writes the manifest with every member's
SHA-256, signs it with Ed25519 and packs the tree the way the APF chart
expects (a gzipped tar, members without a leading "./").

The signature matches `apf-compile genfixture`: Ed25519 over the manifest
document's bytes, then a YamlSigilSignature document. No private image or
Docker is needed.

  apf-bundle.py keygen            # new key pair: seed under ~/.apf-keys, public key in the chart
  apf-bundle.py build             # (re)sign the bundle into the chart when the policy changed
  apf-bundle.py verify            # check the committed bundle: hashes, signature, up to date
"""
import argparse
import base64
import hashlib
import io
import os
import sys
import tarfile
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
POLICY_DIR = ROOT / "charts" / "governance-policy"
APF_DIR = ROOT / "charts" / "governance-interceptor" / "files" / "apf"
BUNDLE = APF_DIR / "bundle.tar.gz"
PUBKEY = APF_DIR / "apf.pub"
SEED = Path(os.environ.get("APF_SEED", "~/.apf-keys/apf.seed")).expanduser()

MANIFEST = "bundle.yaml"
BUNDLE_ID = "secure-agent-workspace"
# The APF chart mounts the keys as apf-dev.seed / apf-dev.pub whatever the key
# id is, and looks the trust root up by this id.
# "apf-dev" is only that mount label: the key behind it is the operator's own,
# generated by `keygen` (seed in Vault, public key in files/apf), never APF's
# public demo key, which the chart's trust root replaces.
KEY_ID = "apf-dev"
SIG_SCHEMA = "YamlSigilSignature.v1alpha1"
SIG_ALG = "ED25519_PUREEDDSA_RAW_RS64_CANONICAL"
POLICY_API = "nvidia.agent-policy-fabric.policy/v1alpha1"
SANDBOX_API = "nvidia.agent-policy-fabric.sandbox/v1alpha1"


def fail(msg):
    sys.exit(f"apf-bundle: {msg}")


def ed25519():
    try:
        from cryptography.hazmat.primitives.asymmetric import ed25519 as ed
    except ImportError:
        fail("needs the 'cryptography' package (python3 -m pip install cryptography)")
    return ed


def raw_public(key):
    from cryptography.hazmat.primitives import serialization as s
    return key.public_key().public_bytes(s.Encoding.Raw, s.PublicFormat.Raw)


def raw_private(key):
    from cryptography.hazmat.primitives import serialization as s
    return key.private_bytes(s.Encoding.Raw, s.PrivateFormat.Raw, s.NoEncryption())


def read_key(path):
    """Key files hold one 'ed25519:<base64>' line; '#' lines are comments."""
    for line in Path(path).read_text().splitlines():
        line = line.strip()
        if line and not line.startswith("#"):
            kind, _, b64 = line.partition(":")
            if kind != "ed25519":
                fail(f"{path}: expected an 'ed25519:<base64>' line")
            return base64.b64decode(b64)
    fail(f"{path}: no key found")


def load_seed():
    if not SEED.exists():
        fail(f"no signing seed at {SEED}; run `make apf-keys` (or set APF_SEED)")
    ed = ed25519()
    key = ed.Ed25519PrivateKey.from_private_bytes(read_key(SEED))
    raw = raw_public(key)
    if not PUBKEY.exists() or read_key(PUBKEY) != raw:
        fail(f"{SEED} does not match {PUBKEY.relative_to(ROOT)}; "
             "use the seed that goes with the committed public key")
    return key


# -- translation ---------------------------------------------------------------

def dump(doc, header):
    return header + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)


HEADER = "# Generated by scripts/apf-bundle.py from charts/governance-policy. Do not edit.\n"


def sandbox_policy(policy):
    spec = {}
    if "filesystem_policy" in policy:
        spec["filesystem"] = policy["filesystem_policy"]
    for key in ("landlock", "process", "network_policies"):
        if key in policy:
            spec[key] = policy[key]
    return {"apiVersion": SANDBOX_API, "kind": "SandboxPolicy",
            "metadata": {"name": "default"}, "spec": spec}


def credential(cred):
    """Only the fields APF's Provider schema accepts (it rejects unknown ones):
    name, envVars, required, style, header."""
    out = {"name": cred["name"], "envVars": list(cred.get("env_vars", [])),
           "required": bool(cred.get("required", False))}
    if "auth_style" in cred:
        out["style"] = cred["auth_style"]
    if "header_name" in cred:
        out["header"] = cred["header_name"]
    return out


# APF 0.2.0 rejects any other field in a Provider spec ("unknown field ...,
# expected one of type, endpoints, binaries, credentials"). OpenShell-only
# profile fields (category, inference_capable, discovery, a credential's
# description and query_param) have no place in it and are left out.
PROVIDER_SPEC_FIELDS = ("type", "endpoints", "binaries", "credentials")


def provider(profile):
    """OpenShell provider profile -> APF Provider. The profile id stays the
    name: it is the provider type users pass to `openshell provider create`."""
    pid = profile["id"]
    meta = {"name": pid}
    if "display_name" in profile:
        meta["title"] = profile["display_name"]
    if "description" in profile:
        meta["description"] = profile["description"]
    spec = {"type": profile.get("provider_type") or pid,
            "endpoints": list(profile.get("endpoints") or [])}
    if profile.get("binaries"):
        spec["binaries"] = list(profile["binaries"])
    if profile.get("credentials"):
        spec["credentials"] = [credential(c) for c in profile["credentials"]]
    assert set(spec) <= set(PROVIDER_SPEC_FIELDS), spec.keys()
    return {"apiVersion": POLICY_API, "kind": "Provider", "metadata": meta, "spec": spec}


def unsupported(profile):
    """Why APF cannot carry this profile, or None. APF's credentials have no
    query parameter name, and OpenShell refuses the whole catalog when a
    query-auth credential comes back without one (seen live: "profile
    'gemini' credentials.query_param: query_param is required for query
    auth"), so such profiles stay out of the bundle."""
    for cred in profile.get("credentials") or []:
        if cred.get("auth_style") == "query":
            return f"credential '{cred['name']}' uses query auth, which APF cannot express"
    return None


def members(policy_dir=None, quiet=False):
    """Bundle member path -> bytes, from governance-policy."""
    policy_dir = policy_dir or POLICY_DIR
    out = {"sandbox/default-policy.yaml":
           dump(sandbox_policy(yaml.safe_load((policy_dir / "policy.yaml").read_text())), HEADER)}
    for path in sorted((policy_dir / "profiles").glob("*.yaml")):
        profile = yaml.safe_load(path.read_text())
        if profile.get("id") != path.stem:
            fail(f"{path}: id must match the file name")
        reason = unsupported(profile)
        if reason:
            if not quiet:
                print(f"apf-bundle: leaving out {path.name}: {reason}", file=sys.stderr)
            continue
        out[f"provider-profiles/{path.name}"] = dump(provider(profile), HEADER)
    return {k: v.encode() for k, v in out.items()}


# -- manifest, signature, tarball ---------------------------------------------

def manifest_body(files, revision):
    lines = [
        "# APF policy bundle for Secure Agent Workspace (scripts/apf-bundle.py).",
        f"apiVersion: {POLICY_API}",
        "kind: PolicyBundle",
        "metadata: {}",
        "",
        f"id: {BUNDLE_ID}",
        'description: "Secure Agent Workspace sandbox policy and provider profiles"',
        f"policy_revision: {revision}",
        'not_before: "2026-01-01T00:00:00Z"',
        'expires_at: "2099-12-31T00:00:00Z"',
        "",
        "manifest:",
    ]
    for path in sorted(files):
        lines += [f"  - path: {path}", f"    sha256: {hashlib.sha256(files[path]).hexdigest()}"]
    return "\n".join(lines) + "\n"


def sign(body, key):
    sig = base64.urlsafe_b64encode(key.sign(body.encode())).decode().rstrip("=")
    return (body + "---\n" + f"schema: {SIG_SCHEMA}\nalg: {SIG_ALG}\n"
            f"keyid: {KEY_ID}\nsignature: {sig}\n")


def split_signed(text):
    body, sep, sig = text.partition("---\n")
    if not sep:
        fail(f"{MANIFEST} has no signature document")
    return body, yaml.safe_load(sig)


def pack(files):
    buf = io.BytesIO()
    with tarfile.open(fileobj=buf, mode="w:gz", format=tarfile.PAX_FORMAT) as tar:
        for path in sorted(files):
            info = tarfile.TarInfo(path)
            info.size, info.mode, info.mtime = len(files[path]), 0o644, 0
            tar.addfile(info, io.BytesIO(files[path]))
    # gzip stores a timestamp; zero it so an unchanged bundle is byte-identical.
    data = bytearray(buf.getvalue())
    data[4:8] = b"\0\0\0\0"
    return bytes(data)


def unpack(path):
    with tarfile.open(path, "r:gz") as tar:
        return {m.name: tar.extractfile(m).read() for m in tar.getmembers() if m.isfile()}


# -- commands ------------------------------------------------------------------

def cmd_keygen(args):
    if SEED.exists() and not args.force:
        fail(f"{SEED} exists; pass --force to replace it (re-sign the bundle afterwards)")
    ed = ed25519()
    key = ed.Ed25519PrivateKey.generate()
    seed = base64.b64encode(raw_private(key)).decode()
    pub = base64.b64encode(raw_public(key)).decode()
    SEED.parent.mkdir(parents=True, exist_ok=True, mode=0o700)
    fd = os.open(SEED, os.O_WRONLY | os.O_CREAT | os.O_TRUNC, 0o600)
    with os.fdopen(fd, "w") as f:
        f.write(f"# APF signing key for Secure Agent Workspace. Keep it out of git.\ned25519:{seed}\n")
    APF_DIR.mkdir(parents=True, exist_ok=True)
    PUBKEY.write_text(f"# APF trust root: verifies the policy bundle (scripts/apf-bundle.py).\ned25519:{pub}\n")
    print(f"seed:       {SEED} (load it into Vault as apf-signing, see values-secret.yaml.template)")
    print(f"public key: {PUBKEY.relative_to(ROOT)} (commit it to your deployment branch)")


def cmd_build(args):
    key = load_seed()
    files = members()
    revision = 1
    if BUNDLE.exists():
        old = unpack(BUNDLE)
        old_body, _ = split_signed(old[MANIFEST].decode())
        revision = int(yaml.safe_load(old_body)["policy_revision"])
        old_members = {k: v for k, v in old.items() if k != MANIFEST}
        if old_members == files and not args.bump:
            print(f"{BUNDLE.relative_to(ROOT)} is up to date (policy_revision {revision})")
            return
        revision += 1
    files[MANIFEST] = sign(manifest_body(files, revision), key).encode()
    APF_DIR.mkdir(parents=True, exist_ok=True)
    BUNDLE.write_bytes(pack(files))
    print(f"wrote {BUNDLE.relative_to(ROOT)} (policy_revision {revision}, "
          f"{len(files) - 1} member(s)); commit it with {PUBKEY.relative_to(ROOT)} to your deployment branch")


def verify(bundle=None, pubkey=None, policy_dir=None, check_current=True):
    """Return a list of problems (empty when the bundle is good)."""
    bundle, pubkey = bundle or BUNDLE, pubkey or PUBKEY
    problems = []
    files = unpack(bundle)
    if MANIFEST not in files:
        return [f"no {MANIFEST} in the bundle"]
    if any(n.startswith(("./", "/")) for n in files):
        problems.append("member names must not start with './' or '/'")
    body, sig = split_signed(files[MANIFEST].decode())
    doc = yaml.safe_load(body)
    listed = {m["path"]: m["sha256"] for m in doc["manifest"]}
    for path, digest in listed.items():
        if path not in files:
            problems.append(f"{path}: listed but missing")
        elif hashlib.sha256(files[path]).hexdigest() != digest:
            problems.append(f"{path}: sha256 mismatch")
    for path in files:
        if path != MANIFEST and path not in listed:
            problems.append(f"{path}: in the tarball but not in the manifest")
    ed = ed25519()
    pub = ed.Ed25519PublicKey.from_public_bytes(read_key(pubkey))
    raw = base64.urlsafe_b64decode(sig["signature"] + "=" * (-len(sig["signature"]) % 4))
    try:
        pub.verify(raw, body.encode())
    except Exception:
        problems.append("signature does not verify against the committed public key")
    if sig.get("keyid") != KEY_ID:
        problems.append(f"keyid {sig.get('keyid')!r}, expected {KEY_ID!r}")
    if check_current:
        current = members(policy_dir, quiet=True)
        if {k: v for k, v in files.items() if k != MANIFEST} != current:
            problems.append("out of date with charts/governance-policy; run `make apf-bundle`")
    return problems


def cmd_verify(args):
    if not BUNDLE.exists():
        fail(f"no bundle at {BUNDLE.relative_to(ROOT)}; run `make apf-keys apf-bundle`")
    problems = verify(check_current=not args.integrity_only)
    for p in problems:
        print(f"FAIL: {p}")
    if problems:
        sys.exit(1)
    print(f"OK: {BUNDLE.relative_to(ROOT)}")


def main():
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    sub = parser.add_subparsers(dest="cmd", required=True)
    p = sub.add_parser("keygen", help="create a signing key pair")
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=cmd_keygen)
    p = sub.add_parser("build", help="sign the bundle when governance-policy changed")
    p.add_argument("--bump", action="store_true", help="re-sign with a new revision even if unchanged")
    p.set_defaults(func=cmd_build)
    p = sub.add_parser("verify", help="check the committed bundle")
    p.add_argument("--integrity-only", action="store_true", help="skip the up-to-date check")
    p.set_defaults(func=cmd_verify)
    args = parser.parse_args()
    args.func(args)


if __name__ == "__main__":
    main()
