apiVersion: saw.redhat.com/v1alpha1
kind: Sandboxes
metadata: {}
spec:
  sandboxes:
    - name: codex
      type: codex
      enabled: true
      image: quay.io/aipcc/base-images/agentic/codex:latest
      providers:
        - openai
