apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshell-gateway.fullname" . }}-gateway
  labels:
    {{- include "openshell-gateway.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    {{- include "openshell-gateway.selectorLabels" . | nindent 4 }}
  ports:
    - name: gateway
      port: 17670
      targetPort: 17670
      protocol: TCP
    - name: ssh
      port: 22
      targetPort: 22
      protocol: TCP
