{{- if .Values.test.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "openshell-gateway.fullname" . }}-test
  labels:
    {{- include "openshell-gateway.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "openshell-gateway.fullname" . }}-test
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "openshell-gateway.fullname" . }}-test
{{- end }}
