{{- if .Values.test.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "openshell-gateway.fullname" . }}-test
  labels:
    {{- include "openshell-gateway.labels" . | nindent 4 }}
{{- end }}
