apiVersion: v1
kind: ConfigMap
metadata:
  name: radicale-config
  labels:
    app.kubernetes.io/name: radicale
    app.kubernetes.io/instance: {{ .Release.Name }}
data:
  config: |
    [server]
    hosts = 0.0.0.0:{{ .Values.httpPort }}
    ssl = false
    [auth]
    type = none
    [storage]
    filesystem_folder = /var/lib/radicale/collections
    [web]
    type = internal
