apiVersion: v1
kind: Service
metadata:
  name: radicale
  labels:
    app.kubernetes.io/name: radicale
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: ClusterIP
  ports:
    - name: cal
      port: {{ .Values.httpPort }}
      targetPort: cal
      protocol: TCP
  selector:
    app.kubernetes.io/name: radicale
