{{- if .Values.accessControl.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "openshell-sandbox.fullname" . }}-auth-proxy
  labels:
    {{- include "openshell-sandbox.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "openshell-sandbox.fullname" . }}-auth-proxy
  ports:
    - name: proxy
      port: 4180
      targetPort: 4180
      protocol: TCP
{{- end }}
