{{- if .Values.route.enabled }}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "openshell-sandbox.fullname" . }}-gateway
  labels:
    {{- include "openshell-sandbox.labels" . | nindent 4 }}
spec:
  {{- if .Values.route.host }}
  host: {{ .Values.route.host }}
  {{- end }}
  to:
    kind: Service
    name: {{ include "openshell-sandbox.fullname" . }}-gateway
    weight: 100
  port:
    targetPort: gateway
  tls:
    termination: passthrough
{{- end }}
