{{- if .Values.vertexSaJson }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "openshell-sandbox.fullname" . }}-gcp-sa
  labels:
    {{- include "openshell-sandbox.labels" . | nindent 4 }}
type: Opaque
stringData:
  sa.json: |
{{ .Values.vertexSaJson | indent 4 }}
{{- end }}
