{{- if eq .Values.sourceMode "snapshot" }}
{{- if .Capabilities.APIVersions.Has "clone.kubevirt.io/v1beta1" }}
apiVersion: clone.kubevirt.io/v1beta1
{{- else }}
apiVersion: clone.kubevirt.io/v1alpha1
{{- end }}
kind: VirtualMachineClone
metadata:
  name: clone-{{ include "openshell-sandbox.fullname" . }}
  labels:
    {{- include "openshell-sandbox.labels" . | nindent 4 }}
    openshell.pattern/component: sandbox
spec:
  source:
    apiGroup: snapshot.kubevirt.io
    kind: VirtualMachineSnapshot
    name: {{ .Values.sourceSnapshot }}
  target:
    apiGroup: kubevirt.io
    kind: VirtualMachine
    name: {{ include "openshell-sandbox.fullname" . }}
  labelFilters:
    - "*"
    - "!kubevirt.io/*"
  annotationFilters:
    - "*"
    - "!kubevirt.io/*"
    - "!kubectl.kubernetes.io/*"
  template:
    labelFilters:
      - "*"
      - "!kubevirt.io/*"
    annotationFilters:
      - "*"
      - "!kubevirt.io/*"
  patches:
    - '{"op":"replace","path":"/spec/template/metadata/labels/app.kubernetes.io~1name","value":"{{ include "openshell-sandbox.fullname" . }}"}'
    - '{"op":"add","path":"/spec/template/metadata/labels/openshell.pattern~1role","value":"gateway"}'
{{- end }}
